create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list aurora_8b10b_exdes_inst_0/aurora_module_i/clock_module_i/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {aurora_rx_data_process_inst/state[0]} {aurora_rx_data_process_inst/state[1]} {aurora_rx_data_process_inst/state[2]} {aurora_rx_data_process_inst/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {aurora_rx_data_process_inst/aurora_rxdata[0]} {aurora_rx_data_process_inst/aurora_rxdata[1]} {aurora_rx_data_process_inst/aurora_rxdata[2]} {aurora_rx_data_process_inst/aurora_rxdata[3]} {aurora_rx_data_process_inst/aurora_rxdata[4]} {aurora_rx_data_process_inst/aurora_rxdata[5]} {aurora_rx_data_process_inst/aurora_rxdata[6]} {aurora_rx_data_process_inst/aurora_rxdata[7]} {aurora_rx_data_process_inst/aurora_rxdata[8]} {aurora_rx_data_process_inst/aurora_rxdata[9]} {aurora_rx_data_process_inst/aurora_rxdata[10]} {aurora_rx_data_process_inst/aurora_rxdata[11]} {aurora_rx_data_process_inst/aurora_rxdata[12]} {aurora_rx_data_process_inst/aurora_rxdata[13]} {aurora_rx_data_process_inst/aurora_rxdata[14]} {aurora_rx_data_process_inst/aurora_rxdata[15]} {aurora_rx_data_process_inst/aurora_rxdata[16]} {aurora_rx_data_process_inst/aurora_rxdata[17]} {aurora_rx_data_process_inst/aurora_rxdata[18]} {aurora_rx_data_process_inst/aurora_rxdata[19]} {aurora_rx_data_process_inst/aurora_rxdata[20]} {aurora_rx_data_process_inst/aurora_rxdata[21]} {aurora_rx_data_process_inst/aurora_rxdata[22]} {aurora_rx_data_process_inst/aurora_rxdata[23]} {aurora_rx_data_process_inst/aurora_rxdata[24]} {aurora_rx_data_process_inst/aurora_rxdata[25]} {aurora_rx_data_process_inst/aurora_rxdata[26]} {aurora_rx_data_process_inst/aurora_rxdata[27]} {aurora_rx_data_process_inst/aurora_rxdata[28]} {aurora_rx_data_process_inst/aurora_rxdata[29]} {aurora_rx_data_process_inst/aurora_rxdata[30]} {aurora_rx_data_process_inst/aurora_rxdata[31]} {aurora_rx_data_process_inst/aurora_rxdata[32]} {aurora_rx_data_process_inst/aurora_rxdata[33]} {aurora_rx_data_process_inst/aurora_rxdata[34]} {aurora_rx_data_process_inst/aurora_rxdata[35]} {aurora_rx_data_process_inst/aurora_rxdata[36]} {aurora_rx_data_process_inst/aurora_rxdata[37]} {aurora_rx_data_process_inst/aurora_rxdata[38]} {aurora_rx_data_process_inst/aurora_rxdata[39]} {aurora_rx_data_process_inst/aurora_rxdata[40]} {aurora_rx_data_process_inst/aurora_rxdata[41]} {aurora_rx_data_process_inst/aurora_rxdata[42]} {aurora_rx_data_process_inst/aurora_rxdata[43]} {aurora_rx_data_process_inst/aurora_rxdata[44]} {aurora_rx_data_process_inst/aurora_rxdata[45]} {aurora_rx_data_process_inst/aurora_rxdata[46]} {aurora_rx_data_process_inst/aurora_rxdata[47]} {aurora_rx_data_process_inst/aurora_rxdata[48]} {aurora_rx_data_process_inst/aurora_rxdata[49]} {aurora_rx_data_process_inst/aurora_rxdata[50]} {aurora_rx_data_process_inst/aurora_rxdata[51]} {aurora_rx_data_process_inst/aurora_rxdata[52]} {aurora_rx_data_process_inst/aurora_rxdata[53]} {aurora_rx_data_process_inst/aurora_rxdata[54]} {aurora_rx_data_process_inst/aurora_rxdata[55]} {aurora_rx_data_process_inst/aurora_rxdata[56]} {aurora_rx_data_process_inst/aurora_rxdata[57]} {aurora_rx_data_process_inst/aurora_rxdata[58]} {aurora_rx_data_process_inst/aurora_rxdata[59]} {aurora_rx_data_process_inst/aurora_rxdata[60]} {aurora_rx_data_process_inst/aurora_rxdata[61]} {aurora_rx_data_process_inst/aurora_rxdata[62]} {aurora_rx_data_process_inst/aurora_rxdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[0]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[1]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[2]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[3]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[4]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[5]} {ddr_top_inst/xdma_vin_ctrl_inst/up_next_state[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 7 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ddr_top_inst/xdma_vin_ctrl_inst/up_state[0]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[1]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[2]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[3]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[4]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[5]} {ddr_top_inst/xdma_vin_ctrl_inst/up_state[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list aurora_rx_data_process_inst/aurora_rxen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ddr_top_inst/xdma_vin_ctrl_inst/aurora_wr_start_flag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list CHANNEL_UP_DONE_0]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list ddr_top_inst/mem_ctrl_inst/ddr3_mig_inst/u_ddr3_mig_mig/u_ddr3_infrastructure/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[0]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[1]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[2]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[3]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[4]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[5]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[6]} {ddr_top_inst/xdma_vin_ctrl_inst/wr_frame_addr_d[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[0]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[1]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[2]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[3]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[4]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[5]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[6]} {ddr_top_inst/xdma_vin_ctrl_inst/rd_frame_addr_d[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list ddr3_init_done]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list aurora_64b66b_exdes_inst_1/aurora_64b66b_0_block_i/clock_module_i/user_clk_net_i_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list CHANNEL_UP_DONE_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_50M]
