
set_property BITSTREAM.CONFIG.BPI_SYNC_MODE Type2 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pulldown [current_design]
set_property CONFIG_MODE BPI16 [current_design]
# Multiboot properties
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 32'h00050000 [current_design]

###############################################################################
# Physical Constraints
###############################################################################

set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN M5 [get_ports {pci_exp_rxn[0]}]
set_property PACKAGE_PIN M6 [get_ports {pci_exp_rxp[0]}]
set_property PACKAGE_PIN L3 [get_ports {pci_exp_txn[0]}]
set_property PACKAGE_PIN L4 [get_ports {pci_exp_txp[0]}]
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN P5 [get_ports {pci_exp_rxn[1]}]
set_property PACKAGE_PIN P6 [get_ports {pci_exp_rxp[1]}]
set_property PACKAGE_PIN M1 [get_ports {pci_exp_txn[1]}]
set_property PACKAGE_PIN M2 [get_ports {pci_exp_txp[1]}]
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN R3 [get_ports {pci_exp_rxn[2]}]
set_property PACKAGE_PIN R4 [get_ports {pci_exp_rxp[2]}]
set_property PACKAGE_PIN N3 [get_ports {pci_exp_txn[2]}]
set_property PACKAGE_PIN N4 [get_ports {pci_exp_txp[2]}]
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN T5 [get_ports {pci_exp_rxn[3]}]
set_property PACKAGE_PIN T6 [get_ports {pci_exp_rxp[3]}]
set_property PACKAGE_PIN P1 [get_ports {pci_exp_txn[3]}]
set_property PACKAGE_PIN P2 [get_ports {pci_exp_txp[3]}]
set_property LOC GTXE2_CHANNEL_X0Y3 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[4].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN V5 [get_ports {pci_exp_rxn[4]}]
set_property PACKAGE_PIN V6 [get_ports {pci_exp_rxp[4]}]
set_property PACKAGE_PIN T1 [get_ports {pci_exp_txn[4]}]
set_property PACKAGE_PIN T2 [get_ports {pci_exp_txp[4]}]
set_property LOC GTXE2_CHANNEL_X0Y2 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[5].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN W3 [get_ports {pci_exp_rxn[5]}]
set_property PACKAGE_PIN W4 [get_ports {pci_exp_rxp[5]}]
set_property PACKAGE_PIN U3 [get_ports {pci_exp_txn[5]}]
set_property PACKAGE_PIN U4 [get_ports {pci_exp_txp[5]}]
set_property LOC GTXE2_CHANNEL_X0Y1 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[6].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN Y5 [get_ports {pci_exp_rxn[6]}]
set_property PACKAGE_PIN Y6 [get_ports {pci_exp_rxp[6]}]
set_property PACKAGE_PIN V1 [get_ports {pci_exp_txn[6]}]
set_property PACKAGE_PIN V2 [get_ports {pci_exp_txp[6]}]
set_property LOC GTXE2_CHANNEL_X0Y0 [get_cells {xdma_0_inst/inst/xdma_0_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[7].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
set_property PACKAGE_PIN AA3 [get_ports {pci_exp_rxn[7]}]
set_property PACKAGE_PIN AA4 [get_ports {pci_exp_rxp[7]}]
set_property PACKAGE_PIN Y1 [get_ports {pci_exp_txn[7]}]
set_property PACKAGE_PIN Y2 [get_ports {pci_exp_txp[7]}]

#########################################################################################################################
# End PCIe Core Constraints
#########################################################################################################################

set_property PACKAGE_PIN U8 [get_ports pcie_sys_clk_p]
set_property PACKAGE_PIN U7 [get_ports pcie_sys_clk_n]

set_property IOSTANDARD LVDS_25 [get_ports FPGA_MASTER_CLOCK_P]
set_property IOSTANDARD LVDS_25 [get_ports FPGA_MASTER_CLOCK_N]
set_property PACKAGE_PIN G13 [get_ports FPGA_MASTER_CLOCK_P]
set_property PACKAGE_PIN F13 [get_ports FPGA_MASTER_CLOCK_N]

set_property IOSTANDARD LVCMOS33 [get_ports pcie_rst_n]
set_property PACKAGE_PIN H20 [get_ports pcie_rst_n]
set_property PULLUP true [get_ports pcie_rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports FPGA_RESET]
set_property PACKAGE_PIN J27 [get_ports FPGA_RESET]

set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN K20 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN K19 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN L18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN L17 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports VCC12V_FAN_EN]
set_property PACKAGE_PIN J23 [get_ports VCC12V_FAN_EN]

set_property IOSTANDARD LVCMOS33 [get_ports FAN_FG]
set_property PACKAGE_PIN D16 [get_ports FAN_FG]

#####################################################
#####################################################


set_property PACKAGE_PIN C8 [get_ports GTXQ2_0_P]
set_property PACKAGE_PIN C7 [get_ports GTXQ2_0_N]
# set_property PACKAGE_PIN J8 [get_ports GTXQ2_1_P]
# set_property PACKAGE_PIN J7 [get_ports GTXQ2_1_N]

##  set_property PACKAGE_PIN F6 [get_ports {RXP[3]}]
##  set_property PACKAGE_PIN F2 [get_ports {TXP[3]}]
##  set_property PACKAGE_PIN G4 [get_ports {RXP[2]}]
##  set_property PACKAGE_PIN H2 [get_ports {TXP[2]}]
##  set_property PACKAGE_PIN H6 [get_ports {RXP[1]}]
##  set_property PACKAGE_PIN J4 [get_ports {TXP[1]}]
##  set_property PACKAGE_PIN K6 [get_ports {RXP[0]}]
##  set_property PACKAGE_PIN K2 [get_ports {TXP[0]}]

set_property PACKAGE_PIN D5 [get_ports RX0N]
set_property PACKAGE_PIN D6 [get_ports RX0P]
set_property PACKAGE_PIN C3 [get_ports TX0N]
set_property PACKAGE_PIN C4 [get_ports TX0P]

set_property PACKAGE_PIN A7 [get_ports RX1N]
set_property PACKAGE_PIN A8 [get_ports RX1P]
set_property PACKAGE_PIN A3 [get_ports TX1N]
set_property PACKAGE_PIN A4 [get_ports TX1P]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP0_TX_DISABLE]
set_property PACKAGE_PIN E24 [get_ports FPGA_SFP0_TX_DISABLE]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP0_IIC_SCL]
set_property PACKAGE_PIN C25 [get_ports FPGA_SFP0_IIC_SCL]

set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_TX_DISABLE]
set_property PACKAGE_PIN G24 [get_ports FPGA_SFP1_TX_DISABLE]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_SFP1_IIC_SCL]
set_property PACKAGE_PIN D27 [get_ports FPGA_SFP1_IIC_SCL]

#####################################################
#####################################################
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_WE_B]
set_property PACKAGE_PIN M25 [get_ports FLASH_WE_B]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_OE_B]
set_property PACKAGE_PIN M24 [get_ports FLASH_OE_B]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_ADV_B]
set_property PACKAGE_PIN M30 [get_ports FLASH_ADV_B]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_WAIT]
set_property PACKAGE_PIN R28 [get_ports FLASH_WAIT]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_CE_B]
set_property PACKAGE_PIN U19 [get_ports FLASH_CE_B]

set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[0]}]
set_property PACKAGE_PIN W22 [get_ports {FLASH_ADDR[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[1]}]
set_property PACKAGE_PIN W21 [get_ports {FLASH_ADDR[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[2]}]
set_property PACKAGE_PIN V24 [get_ports {FLASH_ADDR[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[3]}]
set_property PACKAGE_PIN U24 [get_ports {FLASH_ADDR[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[4]}]
set_property PACKAGE_PIN V22 [get_ports {FLASH_ADDR[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[5]}]
set_property PACKAGE_PIN V21 [get_ports {FLASH_ADDR[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[6]}]
set_property PACKAGE_PIN U23 [get_ports {FLASH_ADDR[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[7]}]
set_property PACKAGE_PIN W24 [get_ports {FLASH_ADDR[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[8]}]
set_property PACKAGE_PIN W23 [get_ports {FLASH_ADDR[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[9]}]
set_property PACKAGE_PIN V20 [get_ports {FLASH_ADDR[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[10]}]
set_property PACKAGE_PIN V19 [get_ports {FLASH_ADDR[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[11]}]
set_property PACKAGE_PIN W26 [get_ports {FLASH_ADDR[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[12]}]
set_property PACKAGE_PIN V25 [get_ports {FLASH_ADDR[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[13]}]
set_property PACKAGE_PIN V30 [get_ports {FLASH_ADDR[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[14]}]
set_property PACKAGE_PIN V29 [get_ports {FLASH_ADDR[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[15]}]
set_property PACKAGE_PIN V27 [get_ports {FLASH_ADDR[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[16]}]
set_property PACKAGE_PIN P22 [get_ports {FLASH_ADDR[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[17]}]
set_property PACKAGE_PIN P21 [get_ports {FLASH_ADDR[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[18]}]
set_property PACKAGE_PIN N24 [get_ports {FLASH_ADDR[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[19]}]
set_property PACKAGE_PIN N22 [get_ports {FLASH_ADDR[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[20]}]
set_property PACKAGE_PIN N21 [get_ports {FLASH_ADDR[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[21]}]
set_property PACKAGE_PIN N20 [get_ports {FLASH_ADDR[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[22]}]
set_property PACKAGE_PIN N19 [get_ports {FLASH_ADDR[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[23]}]
set_property PACKAGE_PIN N26 [get_ports {FLASH_ADDR[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[24]}]
set_property PACKAGE_PIN N25 [get_ports {FLASH_ADDR[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[25]}]
set_property PACKAGE_PIN N30 [get_ports {FLASH_ADDR[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_ADDR[26]}]
set_property PACKAGE_PIN N29 [get_ports {FLASH_ADDR[26]}]

set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[0]}]
set_property PACKAGE_PIN P24 [get_ports {FLASH_DATA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[1]}]
set_property PACKAGE_PIN R25 [get_ports {FLASH_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[2]}]
set_property PACKAGE_PIN R20 [get_ports {FLASH_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[3]}]
set_property PACKAGE_PIN R21 [get_ports {FLASH_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[4]}]
set_property PACKAGE_PIN T20 [get_ports {FLASH_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[5]}]
set_property PACKAGE_PIN T21 [get_ports {FLASH_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[6]}]
set_property PACKAGE_PIN T22 [get_ports {FLASH_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[7]}]
set_property PACKAGE_PIN T23 [get_ports {FLASH_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[8]}]
set_property PACKAGE_PIN U20 [get_ports {FLASH_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[9]}]
set_property PACKAGE_PIN P29 [get_ports {FLASH_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[10]}]
set_property PACKAGE_PIN R29 [get_ports {FLASH_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[11]}]
set_property PACKAGE_PIN P27 [get_ports {FLASH_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[12]}]
set_property PACKAGE_PIN P28 [get_ports {FLASH_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[13]}]
set_property PACKAGE_PIN T30 [get_ports {FLASH_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[14]}]
set_property PACKAGE_PIN P26 [get_ports {FLASH_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DATA[15]}]
set_property PACKAGE_PIN R26 [get_ports {FLASH_DATA[15]}]
#####################################################
#####################################################


############## NET - IOSTANDARD ##################
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[0]}]
set_property PACKAGE_PIN AK6 [get_ports {ddr3_dq[0]}]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[1]}]
set_property PACKAGE_PIN AG7 [get_ports {ddr3_dq[1]}]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[2]}]
set_property PACKAGE_PIN AJ6 [get_ports {ddr3_dq[2]}]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[3]}]
set_property PACKAGE_PIN AK8 [get_ports {ddr3_dq[3]}]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[4]}]
set_property PACKAGE_PIN AK4 [get_ports {ddr3_dq[4]}]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[5]}]
set_property PACKAGE_PIN AJ8 [get_ports {ddr3_dq[5]}]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[6]}]
set_property PACKAGE_PIN AK5 [get_ports {ddr3_dq[6]}]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[7]}]
set_property PACKAGE_PIN AF8 [get_ports {ddr3_dq[7]}]
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[8]}]
set_property PACKAGE_PIN AJ3 [get_ports {ddr3_dq[8]}]
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[9]}]
set_property PACKAGE_PIN AH2 [get_ports {ddr3_dq[9]}]
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[10]}]
set_property PACKAGE_PIN AH6 [get_ports {ddr3_dq[10]}]
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[11]}]
set_property PACKAGE_PIN AJ1 [get_ports {ddr3_dq[11]}]
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[12]}]
set_property PACKAGE_PIN AJ4 [get_ports {ddr3_dq[12]}]
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[13]}]
set_property PACKAGE_PIN AK1 [get_ports {ddr3_dq[13]}]
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[14]}]
set_property PACKAGE_PIN AH5 [get_ports {ddr3_dq[14]}]
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[15]}]
set_property PACKAGE_PIN AJ2 [get_ports {ddr3_dq[15]}]
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[16]}]
set_property PACKAGE_PIN AE4 [get_ports {ddr3_dq[16]}]
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[17]}]
set_property PACKAGE_PIN AE3 [get_ports {ddr3_dq[17]}]
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[18]}]
set_property PACKAGE_PIN AF5 [get_ports {ddr3_dq[18]}]
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[19]}]
set_property PACKAGE_PIN AF1 [get_ports {ddr3_dq[19]}]
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[20]}]
set_property PACKAGE_PIN AF6 [get_ports {ddr3_dq[20]}]
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[21]}]
set_property PACKAGE_PIN AF2 [get_ports {ddr3_dq[21]}]
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[22]}]
set_property PACKAGE_PIN AE5 [get_ports {ddr3_dq[22]}]
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[23]}]
set_property PACKAGE_PIN AG5 [get_ports {ddr3_dq[23]}]
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[24]}]
set_property PACKAGE_PIN AD4 [get_ports {ddr3_dq[24]}]
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[25]}]
set_property PACKAGE_PIN AC4 [get_ports {ddr3_dq[25]}]
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[26]}]
set_property PACKAGE_PIN AE6 [get_ports {ddr3_dq[26]}]
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[27]}]
set_property PACKAGE_PIN AC7 [get_ports {ddr3_dq[27]}]
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[28]}]
set_property PACKAGE_PIN AD3 [get_ports {ddr3_dq[28]}]
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[29]}]
set_property PACKAGE_PIN AC5 [get_ports {ddr3_dq[29]}]
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[30]}]
set_property PACKAGE_PIN AD6 [get_ports {ddr3_dq[30]}]
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[31]}]
set_property PACKAGE_PIN AC2 [get_ports {ddr3_dq[31]}]
set_property SLEW FAST [get_ports {ddr3_dq[32]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[32]}]
set_property PACKAGE_PIN AG15 [get_ports {ddr3_dq[32]}]
set_property SLEW FAST [get_ports {ddr3_dq[33]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[33]}]
set_property PACKAGE_PIN AK16 [get_ports {ddr3_dq[33]}]
set_property SLEW FAST [get_ports {ddr3_dq[34]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[34]}]
set_property PACKAGE_PIN AH15 [get_ports {ddr3_dq[34]}]
set_property SLEW FAST [get_ports {ddr3_dq[35]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[35]}]
set_property PACKAGE_PIN AE16 [get_ports {ddr3_dq[35]}]
set_property SLEW FAST [get_ports {ddr3_dq[36]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[36]}]
set_property PACKAGE_PIN AG14 [get_ports {ddr3_dq[36]}]
set_property SLEW FAST [get_ports {ddr3_dq[37]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[37]}]
set_property PACKAGE_PIN AJ17 [get_ports {ddr3_dq[37]}]
set_property SLEW FAST [get_ports {ddr3_dq[38]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[38]}]
set_property PACKAGE_PIN AK15 [get_ports {ddr3_dq[38]}]
set_property SLEW FAST [get_ports {ddr3_dq[39]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[39]}]
set_property PACKAGE_PIN AH17 [get_ports {ddr3_dq[39]}]
set_property SLEW FAST [get_ports {ddr3_dq[40]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[40]}]
set_property PACKAGE_PIN AJ19 [get_ports {ddr3_dq[40]}]
set_property SLEW FAST [get_ports {ddr3_dq[41]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[41]}]
set_property PACKAGE_PIN AH19 [get_ports {ddr3_dq[41]}]
set_property SLEW FAST [get_ports {ddr3_dq[42]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[42]}]
set_property PACKAGE_PIN AD19 [get_ports {ddr3_dq[42]}]
set_property SLEW FAST [get_ports {ddr3_dq[43]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[43]}]
set_property PACKAGE_PIN AF17 [get_ports {ddr3_dq[43]}]
set_property SLEW FAST [get_ports {ddr3_dq[44]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[44]}]
set_property PACKAGE_PIN AK19 [get_ports {ddr3_dq[44]}]
set_property SLEW FAST [get_ports {ddr3_dq[45]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[45]}]
set_property PACKAGE_PIN AG18 [get_ports {ddr3_dq[45]}]
set_property SLEW FAST [get_ports {ddr3_dq[46]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[46]}]
set_property PACKAGE_PIN AE19 [get_ports {ddr3_dq[46]}]
set_property SLEW FAST [get_ports {ddr3_dq[47]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[47]}]
set_property PACKAGE_PIN AG19 [get_ports {ddr3_dq[47]}]
set_property SLEW FAST [get_ports {ddr3_dq[48]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[48]}]
set_property PACKAGE_PIN AB17 [get_ports {ddr3_dq[48]}]
set_property SLEW FAST [get_ports {ddr3_dq[49]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[49]}]
set_property PACKAGE_PIN AC17 [get_ports {ddr3_dq[49]}]
set_property SLEW FAST [get_ports {ddr3_dq[50]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[50]}]
set_property PACKAGE_PIN AB18 [get_ports {ddr3_dq[50]}]
set_property SLEW FAST [get_ports {ddr3_dq[51]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[51]}]
set_property PACKAGE_PIN AD17 [get_ports {ddr3_dq[51]}]
set_property SLEW FAST [get_ports {ddr3_dq[52]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[52]}]
set_property PACKAGE_PIN AA18 [get_ports {ddr3_dq[52]}]
set_property SLEW FAST [get_ports {ddr3_dq[53]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[53]}]
set_property PACKAGE_PIN AD18 [get_ports {ddr3_dq[53]}]
set_property SLEW FAST [get_ports {ddr3_dq[54]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[54]}]
set_property PACKAGE_PIN AB19 [get_ports {ddr3_dq[54]}]
set_property SLEW FAST [get_ports {ddr3_dq[55]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[55]}]
set_property PACKAGE_PIN AE18 [get_ports {ddr3_dq[55]}]
set_property SLEW FAST [get_ports {ddr3_dq[56]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[56]}]
set_property PACKAGE_PIN AD14 [get_ports {ddr3_dq[56]}]
set_property SLEW FAST [get_ports {ddr3_dq[57]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[57]}]
set_property PACKAGE_PIN AC14 [get_ports {ddr3_dq[57]}]
set_property SLEW FAST [get_ports {ddr3_dq[58]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[58]}]
set_property PACKAGE_PIN AA16 [get_ports {ddr3_dq[58]}]
set_property SLEW FAST [get_ports {ddr3_dq[59]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[59]}]
set_property PACKAGE_PIN AA15 [get_ports {ddr3_dq[59]}]
set_property SLEW FAST [get_ports {ddr3_dq[60]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[60]}]
set_property PACKAGE_PIN AE15 [get_ports {ddr3_dq[60]}]
set_property SLEW FAST [get_ports {ddr3_dq[61]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[61]}]
set_property PACKAGE_PIN Y16 [get_ports {ddr3_dq[61]}]
set_property SLEW FAST [get_ports {ddr3_dq[62]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[62]}]
set_property PACKAGE_PIN AA17 [get_ports {ddr3_dq[62]}]
set_property SLEW FAST [get_ports {ddr3_dq[63]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[63]}]
set_property PACKAGE_PIN AB15 [get_ports {ddr3_dq[63]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[0]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[0]}]
set_property PACKAGE_PIN AH7 [get_ports {ddr3_dqs_p[0]}]
set_property PACKAGE_PIN AJ7 [get_ports {ddr3_dqs_n[0]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[1]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[1]}]
set_property PACKAGE_PIN AG2 [get_ports {ddr3_dqs_p[1]}]
set_property PACKAGE_PIN AH1 [get_ports {ddr3_dqs_n[1]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[2]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[2]}]
set_property PACKAGE_PIN AG4 [get_ports {ddr3_dqs_p[2]}]
set_property PACKAGE_PIN AG3 [get_ports {ddr3_dqs_n[2]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[3]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[3]}]
set_property PACKAGE_PIN AD2 [get_ports {ddr3_dqs_p[3]}]
set_property PACKAGE_PIN AD1 [get_ports {ddr3_dqs_n[3]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[4]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[4]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[4]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[4]}]
set_property PACKAGE_PIN AH16 [get_ports {ddr3_dqs_p[4]}]
set_property PACKAGE_PIN AJ16 [get_ports {ddr3_dqs_n[4]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[5]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[5]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[5]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[5]}]
set_property PACKAGE_PIN AJ18 [get_ports {ddr3_dqs_p[5]}]
set_property PACKAGE_PIN AK18 [get_ports {ddr3_dqs_n[5]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[6]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[6]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[6]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[6]}]
set_property PACKAGE_PIN Y19 [get_ports {ddr3_dqs_p[6]}]
set_property PACKAGE_PIN Y18 [get_ports {ddr3_dqs_n[6]}]
set_property SLEW FAST [get_ports {ddr3_dqs_p[7]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[7]}]
set_property SLEW FAST [get_ports {ddr3_dqs_n[7]}]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[7]}]
set_property PACKAGE_PIN AC16 [get_ports {ddr3_dqs_p[7]}]
set_property PACKAGE_PIN AC15 [get_ports {ddr3_dqs_n[7]}]
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property PACKAGE_PIN AF7 [get_ports {ddr3_dm[0]}]
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property PACKAGE_PIN AK3 [get_ports {ddr3_dm[1]}]
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property PACKAGE_PIN AE1 [get_ports {ddr3_dm[2]}]
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property PACKAGE_PIN AC1 [get_ports {ddr3_dm[3]}]
set_property SLEW FAST [get_ports {ddr3_dm[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[4]}]
set_property PACKAGE_PIN AF15 [get_ports {ddr3_dm[4]}]
set_property SLEW FAST [get_ports {ddr3_dm[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[5]}]
set_property PACKAGE_PIN AF18 [get_ports {ddr3_dm[5]}]
set_property SLEW FAST [get_ports {ddr3_dm[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[6]}]
set_property PACKAGE_PIN AC19 [get_ports {ddr3_dm[6]}]
set_property SLEW FAST [get_ports {ddr3_dm[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[7]}]
set_property PACKAGE_PIN Y15 [get_ports {ddr3_dm[7]}]
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property PACKAGE_PIN AB9 [get_ports {ddr3_addr[0]}]
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property PACKAGE_PIN AA11 [get_ports {ddr3_addr[1]}]
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property PACKAGE_PIN AC10 [get_ports {ddr3_addr[2]}]
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property PACKAGE_PIN AC9 [get_ports {ddr3_addr[3]}]
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property PACKAGE_PIN AB12 [get_ports {ddr3_addr[4]}]
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property PACKAGE_PIN AA8 [get_ports {ddr3_addr[5]}]
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property PACKAGE_PIN AB10 [get_ports {ddr3_addr[6]}]
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property PACKAGE_PIN AA12 [get_ports {ddr3_addr[7]}]
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property PACKAGE_PIN Y11 [get_ports {ddr3_addr[8]}]
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property PACKAGE_PIN AA10 [get_ports {ddr3_addr[9]}]
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property PACKAGE_PIN AE9 [get_ports {ddr3_addr[10]}]
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property PACKAGE_PIN AB8 [get_ports {ddr3_addr[11]}]
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property PACKAGE_PIN AD8 [get_ports {ddr3_addr[12]}]
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property PACKAGE_PIN AA13 [get_ports {ddr3_addr[13]}]
set_property SLEW FAST [get_ports {ddr3_addr[14]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[14]}]
set_property PACKAGE_PIN Y10 [get_ports {ddr3_addr[14]}]
set_property SLEW FAST [get_ports {ddr3_addr[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[15]}]
set_property PACKAGE_PIN AE8 [get_ports {ddr3_addr[15]}]
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property PACKAGE_PIN AC12 [get_ports {ddr3_ba[0]}]
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property PACKAGE_PIN AC11 [get_ports {ddr3_ba[1]}]
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property PACKAGE_PIN AD9 [get_ports {ddr3_ba[2]}]
set_property SLEW FAST [get_ports ddr3_cke]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cke]
set_property PACKAGE_PIN AE10 [get_ports ddr3_cke]
set_property SLEW FAST [get_ports ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property PACKAGE_PIN AJ9 [get_ports ddr3_we_n]
set_property SLEW FAST [get_ports ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property PACKAGE_PIN AK9 [get_ports ddr3_ras_n]
set_property SLEW FAST [get_ports ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property PACKAGE_PIN AG9 [get_ports ddr3_cas_n]
set_property SLEW FAST [get_ports ddr3_cs_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cs_n]
set_property PACKAGE_PIN AH9 [get_ports ddr3_cs_n]
set_property SLEW FAST [get_ports ddr3_odt]
set_property IOSTANDARD SSTL15 [get_ports ddr3_odt]
set_property PACKAGE_PIN AK10 [get_ports ddr3_odt]
set_property SLEW FAST [get_ports ddr3_reset_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_reset_n]
set_property PACKAGE_PIN AE13 [get_ports ddr3_reset_n]
set_property SLEW FAST [get_ports ddr3_ck_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_p]
set_property SLEW FAST [get_ports ddr3_ck_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports ddr3_ck_n]
set_property PACKAGE_PIN AD12 [get_ports ddr3_ck_p]
set_property PACKAGE_PIN AD11 [get_ports ddr3_ck_n]








